### ISSUE TITLE
Documentation typo — ViGEm | How to Install/Remove — "Nefarius Nefarius Gamepad Emulation Bus Driver"

### ISSUE THREAD

**Issue by Formedras** [nefarius/docs.nefarius.at#14]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read [the project documentation](https://docs.nefarius.at/projects/) and not found a solution to my problem there
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

In /docs/projects/ViGEm/How-To-Install.md at line 30, the text says `Nefarius Nefarius Gamepad Emulation Bus Driver`. Images and later text correctly replace the second "Nefarius" with "Virtual".

**Comment by nefarius** [comment]
Thx, fixed!
